<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainTracker.Core\DomainTracker.Core.csproj" />
    <ProjectReference Include="..\DomainTracker.DataAccess\DomainTracker.DataAccess.csproj" />
    <ProjectReference Include="..\DomainTracker.Entities\DomainTracker.Entities.csproj" />
    <ProjectReference Include="..\DomainTracker.DTOs\DomainTracker.DTOs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.*" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

</Project>
